### ISSUE TITLE
cabal file has metadata pointing to other repo

### ISSUE THREAD

**Issue by robinp** [domenkozar/paddle#4]
It points to benaco/paddle, which is also what appears as repository on hackage. Which is quite confusing, since apparently benaco/paddle is from some quite ancient history, with different module structure even.

**Comment by domenkozar** [comment]
I've rewriten their work to use Servant so it's quite a different api. 

Thanks for letting me know, I fixed the cabal file.

**Comment by robinp** [comment]
Thank you!
